import { openDatabase, readProducts } from "#utils/database.js";
import { getSourceByName, setSettings } from "#utils/globals.js";

// Устанавливаем нужное имя ресурса

const SOURCE_NAME = "lg";

const source = await getSourceByName(SOURCE_NAME);
setSettings({ source });

const products = await readProducts(source);
const db = await openDatabase(source);

const sql = "UPDATE products SET category = ?, images = json(?) WHERE id = ?";

const {
  LG_FRIENDS,
  TVS,
  TVS_ACCESSORIES,
  MONITORS,
  HOME_THEATER_SYSTEMS,
  AUDIO_SYSTEMS,
  VIDEO_PLAYERS,
  HOME_ENTERTAINMENT,
  TABLETS,
  MOBILE_PHONE_ACCESSORIES,
  ACCESSORIES,
  BLUETOOTH_HEADSETS_AND_HEADPHONES,
  CAR_AUDIO,
  BLURAY_DVD_PLAYERS,
  VIDEO_SYSTEMS,
  PROJECTORS,
  OUTDOOR_DISPLAYS,
  MEDICAL_IMAGING_TECHNOLOGIES,
  NOTEBOOKS,
  REFRIGERATORS,
  WASHERS,
  DISHWASHERS,
  VACUUM_CLEANERS,
  HOME_APPLIANCES,
  MICROWAVE_OVENS,
  BAKERIES,
  AIR_PURIFIERS,
  WATER_PURIFIERS,
  AIR_CONDITIONERS,
  STYLER,
  COMPUTER,
  LIGHTING,
  STORAGES,

  OTHER_APPLIANCES,
} = source.CATEGORIES;

const replacerData = {
  "Lg friends": LG_FRIENDS,
  "الأجهزة المحمولة: أصدقاء lg": LG_FRIENDS,

  Телевизоры: TVS,
  Televizorlar: TVS,
  Телевізори: TVS,
  Televízory: TVS,
  تلویزیون‌ها: "TVs",
  التليفزيونات: "TVs",
  Televizoriai: TVS,
  Televizori: TVS,
  Τηλεορασεις: TVS,
  Lcd電視: TVS,
  一般电视: TVS,
  Mediaspelare: TVS,
  Téléviseurs: TVS,
  Telerid: TVS,
  Televisor: TVS,
  Televizyon: TVS,
  Televíziók: TVS,
  Televizory: TVS,
  "Oled 電視": TVS,
  "Led 電視": TVS,
  "Mehmonxona televizorlari": TVS,

  "لوازم جانبی تلویزیون های ال جی": TVS_ACCESSORIES,
  "Tv-tillbehör": TVS_ACCESSORIES,
  "Tv príslušenstvo": TVS_ACCESSORIES,
  "لوازم جانبی تلویزیون های ال جی": TVS_ACCESSORIES,
  所有電視配件: TVS_ACCESSORIES,
  "Dodaci za tv": TVS_ACCESSORIES,
  "Αξεσουαρ τηλεορασεων": TVS_ACCESSORIES,
  "Televizorių priedai": TVS_ACCESSORIES,
  "Аксесуари для телевізорів": TVS_ACCESSORIES,
  "Aksesoris tv": TVS_ACCESSORIES,
  "Accessoires tv": TVS_ACCESSORIES,
  "Accesorios tv - audio": TVS_ACCESSORIES,
  "ملحقات التليفزيون": TVS_ACCESSORIES,
  电视配件: TVS_ACCESSORIES,
  "Tv zubehör": TVS_ACCESSORIES,

  "Монітори з тв тюнером": MONITORS,
  Monitorlar: MONITORS,
  Monitory: MONITORS,
  Мониторы: MONITORS,
  Монітори: MONITORS,
  Monitori: MONITORS,
  مانیتور: MONITORS,
  Monitor: MONITORS,
  顯示器: MONITORS,
  显示器: MONITORS,
  Bildskärmar: MONITORS,
  "Màn hình máy tính": MONITORS,
  الشاشات: MONITORS,
  一般显示器: MONITORS,
  Monitoare: MONITORS,
  Οθονες: MONITORS,
  Monitoriai: MONITORS,
  Moniteurs: MONITORS,
  Monitorok: MONITORS,
  "Комерційні продукти": MONITORS,
  Monitores: MONITORS,
  Monitör: MONITORS,
  Monitore: MONITORS,
  "Alle-skjermer": MONITORS,
  商用电视: MONITORS,
  Stanbyme: MONITORS,
  "Màn hình phong cách": MONITORS,

  "Medicinski monitori": MEDICAL_IMAGING_TECHNOLOGIES,
  "Medikal görüntüleme teknolojileri": MEDICAL_IMAGING_TECHNOLOGIES,
  医用显示器: MEDICAL_IMAGING_TECHNOLOGIES,

  "Home Theater System": HOME_THEATER_SYSTEMS,
  "Home theater system": HOME_THEATER_SYSTEMS,
  劇院系列: HOME_THEATER_SYSTEMS,
  "Uy teatri tizimlari": HOME_THEATER_SYSTEMS,
  "Rạp hát tại gia": HOME_THEATER_SYSTEMS,
  "Системи домашнього кінотеатру": HOME_THEATER_SYSTEMS,
  "Kućni bioskopi": HOME_THEATER_SYSTEMS,
  "سیستم‌های سینمای خانگی": HOME_THEATER_SYSTEMS,
  家庭影院: HOME_THEATER_SYSTEMS,
  "المسرح المنزلى": HOME_THEATER_SYSTEMS,
  "Systémy domáceho kiná": HOME_THEATER_SYSTEMS,
  Hemmabiosystem: HOME_THEATER_SYSTEMS,
  "Home cinema": HOME_THEATER_SYSTEMS,
  Ses: HOME_THEATER_SYSTEMS,
  Heimkinosysteme: HOME_THEATER_SYSTEMS,

  Audio: AUDIO_SYSTEMS,
  Аудиосистемы: AUDIO_SYSTEMS,
  "سیستم‌های صوتی": AUDIO_SYSTEMS,
  Аудіо: AUDIO_SYSTEMS,
  "Audio systémy": AUDIO_SYSTEMS,
  "Loa thanh": AUDIO_SYSTEMS,
  Ljud: AUDIO_SYSTEMS,
  "Audio uređaji": AUDIO_SYSTEMS,
  Av: AUDIO_SYSTEMS,
  "Garso technika": AUDIO_SYSTEMS,
  الصوتيات: AUDIO_SYSTEMS,
  "Dàn âm thanh": AUDIO_SYSTEMS,
  音响: AUDIO_SYSTEMS,
  "Barres de son": AUDIO_SYSTEMS,
  Sonido: AUDIO_SYSTEMS,
  "Smart audio": AUDIO_SYSTEMS,
  Soundbar: AUDIO_SYSTEMS,
  Lyd: AUDIO_SYSTEMS,
  "Home audio": AUDIO_SYSTEMS,

  "Blu-ray и dvd-плееры": BLURAY_DVD_PLAYERS,
  "Đầu đĩa": BLURAY_DVD_PLAYERS,
  "همه پخش blu-ray / دستگاه پخش dvd": BLURAY_DVD_PLAYERS,
  蓝光播放器: BLURAY_DVD_PLAYERS,
  燒錄機: BLURAY_DVD_PLAYERS,
  "Blu-ray- och dvd-brännare": BLURAY_DVD_PLAYERS,
  "Optički uređaji": BLURAY_DVD_PLAYERS,
  Dvd刻录机: BLURAY_DVD_PLAYERS,
  "Napędy optyczne": BLURAY_DVD_PLAYERS,
  "Оптические приводы": BLURAY_DVD_PLAYERS,
  "Ổ đĩa quang": BLURAY_DVD_PLAYERS,
  "Dvd a blu-ray mechaniky": BLURAY_DVD_PLAYERS,
  "Optical drive": BLURAY_DVD_PLAYERS,
  "Оптичні приводи": BLURAY_DVD_PLAYERS,
  "Οπτικα μεσα αποθηκευσης": BLURAY_DVD_PLAYERS,
  "Blu-ray dvd players": BLURAY_DVD_PLAYERS,
  "Dvd plejeri": BLURAY_DVD_PLAYERS,
  "Graveurs dvd & blu-ray": BLURAY_DVD_PLAYERS,
  "Stockage réseau nas": BLURAY_DVD_PLAYERS,
  "Polttavat blu-ray ja dvd asemat": BLURAY_DVD_PLAYERS,
  "Optical storage": BLURAY_DVD_PLAYERS,
  "Dvd lejátszók": BLURAY_DVD_PLAYERS,

  Відео: VIDEO_SYSTEMS,
  "Video texnika": VIDEO_SYSTEMS,
  "Video systémy": VIDEO_SYSTEMS,
  Vidéo: VIDEO_SYSTEMS,
  "Vaizdo technika": VIDEO_SYSTEMS,
  "أجهزة الفيديو": VIDEO_SYSTEMS,
  "Home video": VIDEO_SYSTEMS,

  "Video player": VIDEO_PLAYERS,
  影音播放機: VIDEO_PLAYERS,

  "Car audio": CAR_AUDIO,
  Bilstereo: CAR_AUDIO,
  "سیستم‌های صوتی و تصویری اتومبیل": CAR_AUDIO,
  Autoradios: CAR_AUDIO,
  Autoradio: CAR_AUDIO,

  "Home entertainment": HOME_ENTERTAINMENT,
  "Οικιακη ψυχαγωγια": HOME_ENTERTAINMENT,

  Планшеты: TABLETS,

  "لوازم جانبی موبایل‌‌های ال جی": MOBILE_PHONE_ACCESSORIES,
  "Мобільні аксесуари": MOBILE_PHONE_ACCESSORIES,
  "Accessoires mobiles": MOBILE_PHONE_ACCESSORIES,
  Mobiltillbehör: MOBILE_PHONE_ACCESSORIES,
  手机配件: MOBILE_PHONE_ACCESSORIES,
  "Mobiltelefon készülékek": MOBILE_PHONE_ACCESSORIES,
  "Cuffie bluetooth": MOBILE_PHONE_ACCESSORIES,
  "Mobiltelefon tartozékok": MOBILE_PHONE_ACCESSORIES,
  "Aksesoris mobile": MOBILE_PHONE_ACCESSORIES,

  Příslušenstvo: ACCESSORIES,
  "Аксессуары и носимые устройства": ACCESSORIES,
  "Αξεσουαρ υπολογιστων": ACCESSORIES,
  "Egyéb it kiegészítők": ACCESSORIES,
  "Dyski zewnętrzne": ACCESSORIES,
  "Accessoires informatiques": ACCESSORIES,
  "Accesorios pc": ACCESSORIES,
  Almacenamiento: ACCESSORIES,
  "Accessori per pc": ACCESSORIES,
  Akcesoria: ACCESSORIES,

  "Tai nghe không dây": BLUETOOTH_HEADSETS_AND_HEADPHONES,
  真無線藍牙耳機: BLUETOOTH_HEADSETS_AND_HEADPHONES,
  "Портативные bluetooth колонки": BLUETOOTH_HEADSETS_AND_HEADPHONES,
  "Écouteurs bluetooth": BLUETOOTH_HEADSETS_AND_HEADPHONES,
  "Belaidės ausinės": BLUETOOTH_HEADSETS_AND_HEADPHONES,

  投影机: PROJECTORS,
  雷射投影機: PROJECTORS,
  Проекторы: PROJECTORS,
  Projektori: PROJECTORS,
  Projektory: PROJECTORS,
  Projektorer: PROJECTORS,
  Projector: PROJECTORS,
  Проектори: PROJECTORS,
  投影機: PROJECTORS,
  Proyectores: PROJECTORS,
  پروژکتورها: PROJECTORS,
  Projektör: PROJECTORS,
  Beamer: PROJECTORS,
  Projektorok: PROJECTORS,
  "Av projektory": PROJECTORS,
  "Máy chiếu": PROJECTORS,

  "Kommercheskie displei": OUTDOOR_DISPLAYS,
  商用显示器: OUTDOOR_DISPLAYS,
  "Digital signage": OUTDOOR_DISPLAYS,

  Ноутбуки: NOTEBOOKS,
  Notebooki: NOTEBOOKS,
  "Pc portables": NOTEBOOKS,
  Portátil: NOTEBOOKS,
  "Dizüstü bilgisayar": NOTEBOOKS,
  笔记本电脑: NOTEBOOKS,
  Laptopuri: NOTEBOOKS,
  "Bärbara datorer": NOTEBOOKS,
  筆記型電腦: NOTEBOOKS,

  Ordinateurs: COMPUTER,
  Ordenadores: COMPUTER,

  Холодильники: REFRIGERATORS,
  Muzlatgichlar: REFRIGERATORS,
  Ledusskapji: REFRIGERATORS,
  Šaldytuvai: REFRIGERATORS,
  "Kyl & frys": REFRIGERATORS,
  "Aparate frigorifice": REFRIGERATORS,
  Lodówki: REFRIGERATORS,
  Chladničky: REFRIGERATORS,
  "یخچال‌‌ و فریزر": REFRIGERATORS,
  Kulkas: REFRIGERATORS,
  冰箱: REFRIGERATORS,
  "Морозильні камери": REFRIGERATORS,
  Réfrigérateurs: REFRIGERATORS,
  "Tủ lạnh": REFRIGERATORS,
  Ψυγεια: REFRIGERATORS,
  Frižideri: REFRIGERATORS,
  Hűtőszekrények: REFRIGERATORS,
  Frigoríficos: REFRIGERATORS,
  الثلاجات: REFRIGERATORS,
  Frigoriferi: REFRIGERATORS,
  Buzdolabı: REFRIGERATORS,
  Kühlschränke: REFRIGERATORS,
  Mrazničky: REFRIGERATORS,

  "Kir yuvish mashinalari": WASHERS,
  "Стиральные машины": WASHERS,
  "Veš mašine": WASHERS,
  Tvättmaskiner: WASHERS,
  "Пральні машини": WASHERS,
  "Πλυντηρια ρουχων": WASHERS,
  Práčky: WASHERS,
  Skalbyklės: WASHERS,
  洗衣机: WASHERS,
  Pralki: WASHERS,
  "Masini de spalat": WASHERS,
  "دستگاه‌های ماشین لباسشویی": WASHERS,
  "Сушильні машини": WASHERS,
  "غسالات الملابس": WASHERS,
  "Mesin cuci": WASHERS,
  Pesumasinad: WASHERS,
  "Máy giặt": WASHERS,
  "Lave-linge": WASHERS,
  "Sèche-linge": WASHERS,
  Sušičky: WASHERS,
  Džiovintuvai: WASHERS,
  Στεγνωτηρια: WASHERS,
  Lavage: WASHERS,
  "Lavadoras y secadoras": WASHERS,
  Mosógépek: WASHERS,
  "Mašine za sušenje veša": WASHERS,
  Suszarki: WASHERS,
  Vaskemaskiner: WASHERS,
  Lavatrici: WASHERS,
  Lavasciuga: WASHERS,
  "Kombinerade tvätt/torkar": WASHERS,
  Lavavajillas: WASHERS,
  Asciugatrici: WASHERS,
  "Çamaşır makinesi": WASHERS,
  Torktumlare: WASHERS,
  "Kurutma maki̇nesi̇": WASHERS,
  مجففات: WASHERS,
  Trockner: WASHERS,
  Waschmaschinen: WASHERS,
  Pračky: WASHERS,
  Pyykinpesukoneet: WASHERS,
  所有洗衣機: WASHERS,
  "Máy giặt sấy công nghiệp": WASHERS,
  "Smartthinq®": WASHERS,
  "Máy hút ẩm": WASHERS,

  "Umývačky riadu": DISHWASHERS,
  "دستگاه‌های ماشین ظرفشویی": DISHWASHERS,
  "Посудомоечные машины": DISHWASHERS,
  Zmywarki: DISHWASHERS,
  "Посудомийні машини": DISHWASHERS,
  "Lave-vaisselle": DISHWASHERS,
  "Mašine za pranje sudova": DISHWASHERS,
  "Πλυντηρια πιατων": DISHWASHERS,
  Lavastoviglie: DISHWASHERS,
  洗碗机: DISHWASHERS,
  "Bulaşık makinesi": DISHWASHERS,
  "غسالات الأطباق": DISHWASHERS,
  "Myčky nádobí": DISHWASHERS,
  洗碗機: DISHWASHERS,

  Пылесосы: VACUUM_CLEANERS,
  "Chang yutgichlar": VACUUM_CLEANERS,
  جاروبرقی: VACUUM_CLEANERS,
  吸尘器: VACUUM_CLEANERS,
  Vysávače: VACUUM_CLEANERS,
  Dammsugare: VACUUM_CLEANERS,
  Пилососи: VACUUM_CLEANERS,
  "Máy hút bụi": VACUUM_CLEANERS,
  Aspiratoare: VACUUM_CLEANERS,
  Aspirateurs: VACUUM_CLEANERS,
  Usisivači: VACUUM_CLEANERS,
  Aspiradoras: VACUUM_CLEANERS,
  "المكانس الكهربائية": VACUUM_CLEANERS,
  Aspirapolvere: VACUUM_CLEANERS,
  "Ηλεκτρικες σκουπες": VACUUM_CLEANERS,
  "Elektrikli süpürge": VACUUM_CLEANERS,
  Staubsauger: VACUUM_CLEANERS,
  Прахосмукачки: VACUUM_CLEANERS,
  Vysavače: VACUUM_CLEANERS,
  Porszívók: VACUUM_CLEANERS,
  Odkurzacze: VACUUM_CLEANERS,

  小家電: HOME_APPLIANCES,
  Inbyggnadsprodukter: HOME_APPLIANCES,
  "Gas stoves": HOME_APPLIANCES,
  "اجاق گازها": HOME_APPLIANCES,
  "Встраиваемая техника": HOME_APPLIANCES,
  "Вбудована техніка": HOME_APPLIANCES,
  "O'rnatilgan maishiy texnika": HOME_APPLIANCES,
  "Εντοιχιζομενες συσκευες": HOME_APPLIANCES,
  "Vstavané spotrebiče": HOME_APPLIANCES,
  Encastrable: HOME_APPLIANCES,
  Incasso: HOME_APPLIANCES,
  "Innebygde produkter": HOME_APPLIANCES,
  "ساید بای ساید": HOME_APPLIANCES,
  "اجاق گاز": HOME_APPLIANCES,

  "Мікрохвильові печі": MICROWAVE_OVENS,
  "Mikroto'lqinli pechlar": MICROWAVE_OVENS,
  "Микроволновые печи": MICROWAVE_OVENS,
  "Lò vi sóng": MICROWAVE_OVENS,
  "Kuchnie mikrofalowe": MICROWAVE_OVENS,
  "Mikrobangų krosnelės": MICROWAVE_OVENS,
  Mikrolaineahjud: MICROWAVE_OVENS,
  "Mikrotalasne pećnice": MICROWAVE_OVENS,
  Oven: MICROWAVE_OVENS,
  微波炉: MICROWAVE_OVENS,
  "Mikrovlnné rúry": MICROWAVE_OVENS,
  "Micro-onde": MICROWAVE_OVENS,
  "Mikroviļņu krāsnis": MICROWAVE_OVENS,
  "أفران الميكروويف": MICROWAVE_OVENS,
  "Φούρνοι μικροκυμάτων": MICROWAVE_OVENS,
  "Micro-onde lightwave": MICROWAVE_OVENS,
  Microondas: MICROWAVE_OVENS,
  "Cuptoare cu microunde": MICROWAVE_OVENS,
  Microonde: MICROWAVE_OVENS,
  Fırın: MICROWAVE_OVENS,
  Mikrowellen: MICROWAVE_OVENS,
  "Grilles mikrohullámú sütő": MICROWAVE_OVENS,
  "Συντηρητες κρασιων": MICROWAVE_OVENS,

  Хлебопекарни: BAKERIES,
  Хлібопічки: BAKERIES,

  Воздухоочистители: AIR_PURIFIERS,
  "Air purifier": AIR_PURIFIERS,
  "منقي الهواء": AIR_PURIFIERS,

  "Máy lọc nước": WATER_PURIFIERS,
  净水器: WATER_PURIFIERS,

  "Maishiy konditsionerlar": AIR_CONDITIONERS,
  "سیستم‌های تهویه مطبوع دیواری (اسپلیت)": AIR_CONDITIONERS,
  "Кондиціонери спліт": AIR_CONDITIONERS,
  "Кондиционеры для дома": AIR_CONDITIONERS,
  "Echipamente de aer conditionat": AIR_CONDITIONERS,
  "Kyla & värmepumpar för ditt hem": AIR_CONDITIONERS,
  "Klima uređaji": AIR_CONDITIONERS,
  "Điều hòa": AIR_CONDITIONERS,
  一對一變頻空調: AIR_CONDITIONERS,
  "Ac lg dualcool inverter": AIR_CONDITIONERS,
  "Máy điều hòa công nghiệp": AIR_CONDITIONERS,
  "Multi v 室内机": AIR_CONDITIONERS,
  Κλιματισμός: AIR_CONDITIONERS,
  Klimatyzatory: AIR_CONDITIONERS,
  "Напівпромислові системи кондиціювання": AIR_CONDITIONERS,
  空调: AIR_CONDITIONERS,
  Légkondicionálók: AIR_CONDITIONERS,
  "Vazdušne toplotne pumpe": AIR_CONDITIONERS,
  "Køling & varmepumper til dit hjem": AIR_CONDITIONERS,
  "Kjøle og varmepumper for ditt hjem": AIR_CONDITIONERS,
  "Climatisation et chauffage": AIR_CONDITIONERS,
  "Aire acondicionado doméstico": AIR_CONDITIONERS,
  "Linea residenziale": AIR_CONDITIONERS,
  "Linea multi split": AIR_CONDITIONERS,
  "Therma v": AIR_CONDITIONERS,
  "Linea commerciale": AIR_CONDITIONERS,
  "Linea multi v": AIR_CONDITIONERS,
  Inverter: AIR_CONDITIONERS,
  Klasik: AIR_CONDITIONERS,
  Klima: AIR_CONDITIONERS,
  "Air care": AIR_CONDITIONERS,
  "Einzel-split klimageräte": AIR_CONDITIONERS,
  "Multi-v klimageräte": AIR_CONDITIONERS,
  Klimageräte: AIR_CONDITIONERS,
  Климатици: AIR_CONDITIONERS,
  "Komerční klimatizace": AIR_CONDITIONERS,
  "Klimatizace pro obytné budovy": AIR_CONDITIONERS,
  Single: AIR_CONDITIONERS,
  Multi: AIR_CONDITIONERS,
  一對多變頻空調: AIR_CONDITIONERS,
  "مكيفات الهواء السكنية": AIR_CONDITIONERS,

  Styler: STYLER,
  "Lg styler 蒸汽衣物护理机": STYLER,
  "برای مراقبت از لباس": STYLER,
  "Styler 蒸氣電子衣櫥": STYLER,

  "Iluminación led": LIGHTING,
  "Φωτισμος led": LIGHTING,

  Almacenamiento: STORAGES,
  "Eksterni hard diskovi": STORAGES,
  "Σκληροι δισκοι": STORAGES,

  其他配件: OTHER_APPLIANCES,
  "Ostali proizvodi": OTHER_APPLIANCES,
  Otros: OTHER_APPLIANCES,
  趣拍得: OTHER_APPLIANCES,
  "Pra.l": OTHER_APPLIANCES,
  美容产品: OTHER_APPLIANCES,
};

const categoriesNotTranslated = [];

for (const product of products) {
  const category = replacerData[product.category] || product.category;

  if (!Object.values(source.CATEGORIES).includes(category)) {
    categoriesNotTranslated.push(category);
  }

  const images = JSON.parse(product.images)
    .filter((image) => !image.includes("no content"))
    .map((image) =>
      image.startsWith("http") ? image : `https://lg.com${image}`
    );

  const values = [category, JSON.stringify(images), product.id];

  await db.run(sql, values, function (err) {
    if (err) return log.error(err.message);
  });
}

console.log(...[new Set(categoriesNotTranslated)]);
