import SOURCE from "#sources/lg/constants.js";

const {
  OWNERS_MANUAL,
  MANUAL,
  QUICK_SETUP_GUIDE,
  USER_GUIDE,
  INSTALLATION_MANUAL,
  QUICK_START_GUIDE,
  BROCHURE,
  SPECIFICATION,
} = SOURCE.MATERIAL_TYPES;

export const replacerData = {
  "Owner’s Manual": OWNERS_MANUAL,
  Användarmanual: OWNERS_MANUAL,
  "دفترچه راهنما": OWNERS_MANUAL,
  "Інструкція користувача": OWNERS_MANUAL,
  "Foydalanuvchi qoʻllanmasi": OWNERS_MANUAL,
  "Руководство пользователя": OWNERS_MANUAL,
  "Príručka používateľa": OWNERS_MANUAL,
  "Priručnik za vlasnika": OWNERS_MANUAL,
  "Manual de Usuario": OWNERS_MANUAL,
  "Sách hướng dẫn sử dụng": OWNERS_MANUAL,
  "دليل المالك": OWNERS_MANUAL,
  "HƯỚNG DẪN SỬ DỤNG": OWNERS_MANUAL,
  "Manuel utilisateur": OWNERS_MANUAL,
  "Guía de Usuario": OWNERS_MANUAL,
  使用指南: OWNERS_MANUAL,
  "Užívateľská príručka": OWNERS_MANUAL,
  用户手册: OWNERS_MANUAL,
  Instruktionsbog: OWNERS_MANUAL,
  "Instrukcja obsługi": OWNERS_MANUAL,
  "NAUDOTOJO VADOVAS": OWNERS_MANUAL,
  "Manualul proprietarului": OWNERS_MANUAL,
  KASUTUSJUHIS: OWNERS_MANUAL,
  "Lietotāja rokasgrāmata": OWNERS_MANUAL,
  "Οδηγός Χρήσης": OWNERS_MANUAL,
  Brukermanual: OWNERS_MANUAL,
  "Felhasználói kézikönyv": OWNERS_MANUAL,
  "Podręcznik użytkownika": OWNERS_MANUAL,
  "Manuale utente": OWNERS_MANUAL,
  "Ръководство на собственика": OWNERS_MANUAL,
  "Korisnički priručnik": OWNERS_MANUAL,
  "Příručka uživatele": OWNERS_MANUAL,
  "Uživatelská příručka": OWNERS_MANUAL,
  Brugervejledning: OWNERS_MANUAL,
  Käyttöopas: OWNERS_MANUAL,

  "Additional Link": MANUAL,
  使用手冊: MANUAL,
  产品说明书: MANUAL,
  "Buku Manual": MANUAL,
  "MONTAJ BOʻYIChA KOʻRSATMALAR": MANUAL,
  "Εγχειρίδιο Χρήσης": MANUAL,
  Kasutusjuhend: MANUAL,
  "Дополнительная ссылка": MANUAL,
  "Lien supplémentaire": MANUAL,
  "Enlaces y Recursos Adicionales": MANUAL,
  "Link Aggiuntivi": MANUAL,
  "Zusätzlicher Link": MANUAL,
  "Допълнителна връзка": MANUAL,
  Ažuriranje: MANUAL,
  "Dodatna poveznica": MANUAL,
  "Další odkaz": MANUAL,
  "Yderligere link": MANUAL,
  "Täiendav link": MANUAL,
  "Πρόσθετα Link": MANUAL,
  Frissítés: MANUAL,
  "Kiegészítő hivatkozás": MANUAL,
  "Papildu saite": MANUAL,
  "Papildoma nuoroda": MANUAL,
  "Ekstra Link": MANUAL,
  "Fisa de informatii": MANUAL,
  "Link aditional": MANUAL,
  "Dodatna veza": MANUAL,
  "Ďalší odkaz": MANUAL,
  Uppdatera: MANUAL,
  "Ytterligare länk": MANUAL,
  附加链接: MANUAL,
  "Tautan Tambahan": MANUAL,
  更新: MANUAL,
  更多鏈結: MANUAL,
  "Liên kết bổ sung": MANUAL,
  "Qoʻshimcha havola": MANUAL,
  "روابط إضافية": MANUAL,
  "Feature Guide": MANUAL,
  "Additional Links": MANUAL,

  快速安装指南: QUICK_SETUP_GUIDE,
  "HƯỚNG DẪN THIẾT LẬP NHANH": QUICK_SETUP_GUIDE,
  "PRÍRUČKA RÝCHLEHO NASTAVENIE": QUICK_SETUP_GUIDE,
  快速設定指南: QUICK_SETUP_GUIDE,
  "راهنمای تنظیم سریع": QUICK_SETUP_GUIDE,
  "Panduan Quick Start": QUICK_SETUP_GUIDE,
  "GUIDE DINSTALLATION RAPIDE": QUICK_SETUP_GUIDE,
  "Guida di Configurazione Rapida": QUICK_SETUP_GUIDE,
  "GUÍA DE INSTALACIÓN RÁPIDA": QUICK_SETUP_GUIDE,
  "Tez sozlash boʻyicha koʻrsatmalar": QUICK_SETUP_GUIDE,
  "GHID DE CONFIGURARE RAPIDA": QUICK_SETUP_GUIDE,
  Snabbuppsättningsguide: QUICK_SETUP_GUIDE,
  "Инструкция для быстрой настройки": QUICK_SETUP_GUIDE,
  "GREITO ĮDIEGIMO VADOVAS": QUICK_SETUP_GUIDE,
  "Vodič za brzo podešavanje": QUICK_SETUP_GUIDE,
  "دليل الإعداد لكويك ستارت": QUICK_SETUP_GUIDE,
  "Γρήγορος Οδηγός Εγκατάστασης": QUICK_SETUP_GUIDE,
  Hurtigsetupsguide: QUICK_SETUP_GUIDE,
  "HIZLI KURULUM KILAVUZU": QUICK_SETUP_GUIDE,
  "Ръководство за бърза настройка": QUICK_SETUP_GUIDE,
  "Vodič za brzo postavljanje": QUICK_SETUP_GUIDE,
  "PŘÍRUČKA RYCHLÉHO NASTAVENÍ": QUICK_SETUP_GUIDE,
  "Gyors beállítási útmutató": QUICK_SETUP_GUIDE,
  "Skrócona Instrukcja Obsługi": QUICK_SETUP_GUIDE,

  "Panduan Pengguna": USER_GUIDE,
  Användarguide: USER_GUIDE,
  "راهنمای کاربر": USER_GUIDE,
  "Guide utilisateur": USER_GUIDE,
  "Vodič za korisnike": USER_GUIDE,
  Brukerguide: USER_GUIDE,
  "Naudotojo vadovas": USER_GUIDE,
  "Довідник користувач": USER_GUIDE,
  "Ghidul Utilizatorului": USER_GUIDE,
  "دليل المستخدم": USER_GUIDE,
  "Felhasználói útmutató": USER_GUIDE,
  "Guida d' uso": USER_GUIDE,
  "Kullanıcı kılavuzu": USER_GUIDE,
  "KULLANICI REHBERİ": USER_GUIDE,
  Benutzerhandbuch: USER_GUIDE,
  "Ръководство за потребителя": USER_GUIDE,
  "USER GUIDE": USER_GUIDE,

  "MANUAL DE INSTALACIÓN": INSTALLATION_MANUAL,
  "HƯỚNG DẪN CÀI ĐẶT": INSTALLATION_MANUAL,
  安装手册: INSTALLATION_MANUAL,
  "MANUALE D’INSTALLAZIONE": INSTALLATION_MANUAL,
  "MANUAL DE INSTALARE": INSTALLATION_MANUAL,
  INSTALLATIONSANVISNINGAR: INSTALLATION_MANUAL,
  "Руководство по установке": INSTALLATION_MANUAL,
  "ИНСТРУКЦИЯ ПО МОНТАЖУ": INSTALLATION_MANUAL,
  "Priručnik za instalaciju": INSTALLATION_MANUAL,
  "Εγχειρίδιο Εγκατάστασης": INSTALLATION_MANUAL,
  "INSTALLASJONS HÅNDBOK": INSTALLATION_MANUAL,
  "Panduan Instalasi": INSTALLATION_MANUAL,
  Installationsvejledning: INSTALLATION_MANUAL,
  "MANUEL DINSTALLATION": INSTALLATION_MANUAL,
  "INSTRUKCJA MONTAŻU": INSTALLATION_MANUAL,
  "Üzembe helyezési kézikönyv": INSTALLATION_MANUAL,
  MONTAGEANLEITUNG: INSTALLATION_MANUAL,
  "Ръководство за монтаж": INSTALLATION_MANUAL,
  "MONTÁŽNY MANUÁL": INSTALLATION_MANUAL,
  "MONTÁŽNÍ MANUÁL": INSTALLATION_MANUAL,
  ASENNUSOHJE: INSTALLATION_MANUAL,
  ASENNUSOPAS: INSTALLATION_MANUAL,
  "دليل التثبيت": INSTALLATION_MANUAL,

  "Qisqa qoʻllanma": QUICK_START_GUIDE,
  "Краткое руководство": QUICK_START_GUIDE,
  "Hurtig vejledning": QUICK_START_GUIDE,
  "SKRÓCONY PODRĘCZNIK OBSŁUGI": QUICK_START_GUIDE,
  "HIZLI BAŞLANGIÇ KILAVUZU": QUICK_START_GUIDE,
  Schnellstartanleitung: QUICK_START_GUIDE,
  "Gyors használatba vételi útmutató": QUICK_START_GUIDE,
  "Ghid de pornire rapida": QUICK_START_GUIDE,

  Katalog: BROCHURE,
  Brožura: BROCHURE,
  Brosura: BROCHURE,

  "Specifikace produktů": SPECIFICATION,
  Specificatii: SPECIFICATION,
  Špecifikácie: SPECIFICATION,
};
